version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend-network
    restart: unless-stopped
    volumes:
      # Mount source code for development (remove in production)
      - ./backend:/app
    environment:
      - PYTHONPATH=/app

networks:
  backend-network:
    driver: bridge
