version: '3.8'

services:
  # Vue.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: unless-stopped
    # Note: Remove depends_on since backend runs separately

networks:
  app-network:
    driver: bridge
