services:
  backend:
    build: ./backend
    container_name: backend_service
    environment:
      - SQUARE_APPLICATION_ID=${SQUARE_APPLICATION_ID}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "8000:8000"

  frontend:
    build: ./
    container_name: frontend_service
    ports:
      - "3000:80"   # Map host 3000 → container's Nginx 80
    depends_on:
      - backend
